name: dogfydiet
description: "A Flutter onboarding app for Dogfy Diet."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  go_router: ^14.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/lotties/
